### ISSUE TITLE
Supprimer une reservation

### ISSUE THREAD

**Issue by cedricst** [oiraMm/ProjetCarPark#4]
On peux supprimer une reservation accepter et terminé, c'est peut-être pas top pour le suivie non?

**Comment by oiraMm** [comment]
Possible de supprimer réservation que lorsque que la résa est en status 'En attente'

**Comment by cedricst** [comment]
Quand je vais dans mes reservation, je peux toutes les supprimer

![image](https://user-images.githubusercontent.com/30894003/29183162-f1fa98ee-7e01-11e7-9bc3-938037c26d98.png)
