### ISSUE TITLE
valider deux reservations avec la meme voiture sur la meme plage date

### ISSUE THREAD

**Issue by cedricst** [oiraMm/ProjetCarPark#5]
![image](https://user-images.githubusercontent.com/30894003/29171306-6a8c0dcc-7ddc-11e7-8075-c240caf42c61.png)

**Comment by oiraMm** [comment]
Pas possible pour moi! je sais pas comment tu as fais..

**Comment by cedricst** [comment]
j'ai créé les deux en meme temps, ensuite je suis allé dans validation et j'ai pu valider les deux
